# Generated by Django 5.0.6 on 2024-06-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_dpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
